name: Build and Push

on: [push, pull_request]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: sudomabider
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build v1 Image
        uses: actions/docker/cli@master
        with: 
          args: build --pull -f composer/Dockerfile --build-arg VERSION=1 -t sudomabider/composer:1 composer
      - name: Tag latest
        uses: actions/docker/cli@master
        with: 
          args: tag sudomabider/composer:1 sudomabider/composer:latest
  push_v1:
    runs-on: ubuntu-latest
    needs: [login, build]
    steps:
      - uses: actions/docker/cli@master
        with: 
          args: push sudomabider/composer:1
  push_latest:
    runs-on: ubuntu-latest
    needs: [login, build]
    steps:
      - uses: actions/docker/cli@master
        with: 
          args: push sudomabider/composer:latest
